GET http://127.0.0.1:5000/admin
Cookie: session=.eJydTktqwzAUvIrROgTZT7Ik36BnaIOR3gcLXDtYEjSE3L2GbrLuapgfM081yxrLwkVNn0_V1RNUaYhcirqojy1j3jvirnDJX01rga3jn1z3sl_V7XX5R-d2OUcPLoua6tH4ZJnUpMQKGKEAlsbBjsCiwenemOA0U_QUGQafRpYBkViE2fSEkYxJkTCwpN6DlR4YrAtB-8TB0yAAnARkDMmhA_HYu-ADikZ0brQ8ajIwyHl9boWPvzeRvvN2Spl4q7k-rrHVZa6PO6tpa-v65rzlX7-t4Gr2.aA508A.AekpPp3js1XfTsE_0ZvTivP-dNk

