POST http://127.0.0.1:5000/crear_usuario
Content-Type: application/json

{
    "nombre": "Xavier",
    "correo": "xavier@gmail.com"
}

###

GET http://127.0.0.1:5000/usuarios

###
GET http://127.0.0.1:5000/info